/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.covid19.contactbase.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.covid19.contactbase.client.model.SpatialTemporalStamp;

/**
 * Contact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-29T10:43:30.347+05:30")
public class Contact {
  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("spatialTemporalStamps")
  private List<SpatialTemporalStamp> spatialTemporalStamps = null;

  public Contact deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Contact spatialTemporalStamps(List<SpatialTemporalStamp> spatialTemporalStamps) {
    this.spatialTemporalStamps = spatialTemporalStamps;
    return this;
  }

  public Contact addSpatialTemporalStampsItem(SpatialTemporalStamp spatialTemporalStampsItem) {
    if (this.spatialTemporalStamps == null) {
      this.spatialTemporalStamps = new ArrayList<SpatialTemporalStamp>();
    }
    this.spatialTemporalStamps.add(spatialTemporalStampsItem);
    return this;
  }

   /**
   * Get spatialTemporalStamps
   * @return spatialTemporalStamps
  **/
  @ApiModelProperty(value = "")
  public List<SpatialTemporalStamp> getSpatialTemporalStamps() {
    return spatialTemporalStamps;
  }

  public void setSpatialTemporalStamps(List<SpatialTemporalStamp> spatialTemporalStamps) {
    this.spatialTemporalStamps = spatialTemporalStamps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contact contact = (Contact) o;
    return Objects.equals(this.deviceId, contact.deviceId) &&
        Objects.equals(this.spatialTemporalStamps, contact.spatialTemporalStamps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, spatialTemporalStamps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contact {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    spatialTemporalStamps: ").append(toIndentedString(spatialTemporalStamps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

