/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.covid19.contactbase.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * QueryRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-29T10:43:30.347+05:30")
public class QueryRequest {
  @SerializedName("fromDateStamp")
  private String fromDateStamp = null;

  @SerializedName("geoHashes")
  private List<String> geoHashes = null;

  @SerializedName("toDateStamp")
  private String toDateStamp = null;

  public QueryRequest fromDateStamp(String fromDateStamp) {
    this.fromDateStamp = fromDateStamp;
    return this;
  }

   /**
   * Get fromDateStamp
   * @return fromDateStamp
  **/
  @ApiModelProperty(value = "")
  public String getFromDateStamp() {
    return fromDateStamp;
  }

  public void setFromDateStamp(String fromDateStamp) {
    this.fromDateStamp = fromDateStamp;
  }

  public QueryRequest geoHashes(List<String> geoHashes) {
    this.geoHashes = geoHashes;
    return this;
  }

  public QueryRequest addGeoHashesItem(String geoHashesItem) {
    if (this.geoHashes == null) {
      this.geoHashes = new ArrayList<String>();
    }
    this.geoHashes.add(geoHashesItem);
    return this;
  }

   /**
   * Get geoHashes
   * @return geoHashes
  **/
  @ApiModelProperty(value = "")
  public List<String> getGeoHashes() {
    return geoHashes;
  }

  public void setGeoHashes(List<String> geoHashes) {
    this.geoHashes = geoHashes;
  }

  public QueryRequest toDateStamp(String toDateStamp) {
    this.toDateStamp = toDateStamp;
    return this;
  }

   /**
   * Get toDateStamp
   * @return toDateStamp
  **/
  @ApiModelProperty(value = "")
  public String getToDateStamp() {
    return toDateStamp;
  }

  public void setToDateStamp(String toDateStamp) {
    this.toDateStamp = toDateStamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRequest queryRequest = (QueryRequest) o;
    return Objects.equals(this.fromDateStamp, queryRequest.fromDateStamp) &&
        Objects.equals(this.geoHashes, queryRequest.geoHashes) &&
        Objects.equals(this.toDateStamp, queryRequest.toDateStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromDateStamp, geoHashes, toDateStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRequest {\n");
    
    sb.append("    fromDateStamp: ").append(toIndentedString(fromDateStamp)).append("\n");
    sb.append("    geoHashes: ").append(toIndentedString(geoHashes)).append("\n");
    sb.append("    toDateStamp: ").append(toIndentedString(toDateStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

