/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.covid19.contactbase.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SpatialTemporalStamp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-29T00:28:16.839+05:30")
public class SpatialTemporalStamp {
  @SerializedName("dateStamp")
  private String dateStamp = null;

  @SerializedName("geohash")
  private String geohash = null;

  public SpatialTemporalStamp dateStamp(String dateStamp) {
    this.dateStamp = dateStamp;
    return this;
  }

   /**
   * Get dateStamp
   * @return dateStamp
  **/
  @ApiModelProperty(value = "")
  public String getDateStamp() {
    return dateStamp;
  }

  public void setDateStamp(String dateStamp) {
    this.dateStamp = dateStamp;
  }

  public SpatialTemporalStamp geohash(String geohash) {
    this.geohash = geohash;
    return this;
  }

   /**
   * Get geohash
   * @return geohash
  **/
  @ApiModelProperty(value = "")
  public String getGeohash() {
    return geohash;
  }

  public void setGeohash(String geohash) {
    this.geohash = geohash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpatialTemporalStamp spatialTemporalStamp = (SpatialTemporalStamp) o;
    return Objects.equals(this.dateStamp, spatialTemporalStamp.dateStamp) &&
        Objects.equals(this.geohash, spatialTemporalStamp.geohash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateStamp, geohash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpatialTemporalStamp {\n");
    
    sb.append("    dateStamp: ").append(toIndentedString(dateStamp)).append("\n");
    sb.append("    geohash: ").append(toIndentedString(geohash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

